version: "3.8"
services:
  agent:
    build: .
    restart: always
    environment:
      WHOAMI: ${WHOAMI}
      RABBITMQ_DEFAULT_AGENT: ${RABBITMQ_DEFAULT_AGENT}
      RABBITMQ_DEFAULT_AGENT_PASS: ${RABBITMQ_DEFAULT_AGENT_PASS}
      LLAMA2_ENDPOINT: ${LLAMA2_ENDPOINT}
      LLAMA2_API_KEY: ${LLAMA2_API_KEY}