version: "3.8"
services:
  RabbitMQCluster01:
    image: rabbitmq:3-management
    container_name: RabbitMQCluster01
    restart: always
    networks:
      - frontend-network
      - backend-network
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      WHOAMI: ${WHOAMI}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq" 
      - "./init-rabbitmq.sh:/init-rabbitmq.sh"
    command: bash -c "/init-rabbitmq.sh && rabbitmq-server"

  www:
    container_name: nginx
    build: nginx
    restart: always
    ports:
      - 81:81
    networks:
      - frontend-network

  groot:
    build: groot
    restart: always
    environment:
      WHOAMI: ${WHOAMI}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - backend-network    

volumes:
  rabbitmq-data:
networks:
  backend-network:
  frontend-network: