version: "3.8"
services:
  agent:
    build: .
    restart: always
    environment:
      WHOAMI: ${WHOAMI}
      RABBITMQ_DEFAULT_AGENT: ${RABBITMQ_DEFAULT_AGENT}
      RABBITMQ_DEFAULT_AGENT_PASS: ${RABBITMQ_DEFAULT_AGENT_PASS}
      GOOGLE_CLOUD_SERVER: ${GOOGLE_CLOUD_SERVER}
      GOOGLE_CLOUD_JSON: ${GOOGLE_CLOUD_JSON}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}