version: "3.8"
services:
  yandexgpt:
    build: .
    restart: always
    environment:
      WHOAMI: ${WHOAMI}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      YANDEXCLOUD_API_KEY: ${YANDEXCLOUD_API_KEY}