version: "3.8"
services:
  router:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      WHOAMI: ${WHOAMI}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    command: bash -c "rabbitmq-server"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq" 
      - "./initrabbitmq.sh:/initrabbitmq.sh"
    networks:
      - mycelium

  www:
    build: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - mycelium

networks:
  mycelium: {}

volumes:
  rabbitmq-data:
