name: Stage Build and Deploy

on:
  push:
    branches:
      - stage
    paths:
      - 'transport/**'
      - 'groot/**'

jobs:
  build-transport:
    if: contains(github.event.head_commit.modified, 'transport/') || contains(github.event.head_commit.added, 'transport/')
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker environment
      run: |
        echo "WHOAMI=Stage" >> $GITHUB_ENV

    - name: Set up SSH keys
      run: |
        echo "${{ secrets.STAGE_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.STAGE_IP_ADDRESS }} >> ~/.ssh/known_hosts

    - name: Set-up environmental files
      run: |
        ssh -i private_key.pem ${{ secrets.STAGE_SSH_USER }}@${{ secrets.STAGE_IP_ADDRESS }} "cd ~/"${GITHUB_REPOSITORY##*/transport/}" && echo "WHOAMI = Stage" > .env && echo "RABBITMQ_DEFAULT_USER = ${{ secrets.RABBITMQ_DEFAULT_USER }}" >> .env && echo "RABBITMQ_DEFAULT_PASS = ${{ secrets.RABBITMQ_DEFAULT_PASS }}" >> .env"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Build
      run: |
        ssh -i private_key.pem ${{ secrets.STAGE_SSH_USER }}@${{ secrets.STAGE_IP_ADDRESS }} "cd ~/"${GITHUB_REPOSITORY##*/transport/}" && git pull origin stage && docker-compose build"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    
    - name: Re-launch
      run: |
        ssh -i private_key.pem ${{ secrets.STAGE_SSH_USER }}@${{ secrets.STAGE_IP_ADDRESS }} "cd ~/"${GITHUB_REPOSITORY##*/transport/}" && docker-compose down && docker-compose up -d"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

  build-groot:
    if: contains(github.event.head_commit.modified, 'groot/') || contains(github.event.head_commit.added, 'groot/')
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker environment
      run: |
        echo "WHOAMI=Stage" >> $GITHUB_ENV

    - name: Set up SSH keys
      run: |
        echo "${{ secrets.STAGE_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.STAGE_IP_ADDRESS }} >> ~/.ssh/known_hosts

    - name: Set-up environmental files
      run: |
        ssh -i private_key.pem ${{ secrets.STAGE_SSH_USER }}@${{ secrets.STAGE_IP_ADDRESS }} "cd ~/"${GITHUB_REPOSITORY##*/groot/}" && echo "WHOAMI = Stage" > .env"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Build
      run: |
        ssh -i private_key.pem ${{ secrets.STAGE_SSH_USER }}@${{ secrets.STAGE_IP_ADDRESS }} "cd ~/"${GITHUB_REPOSITORY##*/groot/}" && git pull origin stage && docker-compose build"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    
    - name: Re-launch
      run: |
        ssh -i private_key.pem ${{ secrets.STAGE_SSH_USER }}@${{ secrets.STAGE_IP_ADDRESS }} "cd ~/"${GITHUB_REPOSITORY##*/groot/}" && docker-compose down && docker-compose up -d"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}