name: Build and Deploy YandexGPT - Test

on:
  push:
    branches:
      - test
    paths:
      - 'yandexgpt/**'
  workflow_dispatch:
  
jobs:
  build-yandexgpt:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up SSH keys
      run: |
        echo "${{ secrets.TEST_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.TEST_IP_ADDRESS }} >> ~/.ssh/known_hosts

    - name: Pull updates
      run: |
        ssh -i private_key.pem ${{ secrets.TEST_SSH_USER }}@${{ secrets.TEST_IP_ADDRESS }} "cd ~/${GITHUB_REPOSITORY##*/} && git fetch origin test && git reset --hard origin/test"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Set-up environmental files
      run: |
        ssh -i private_key.pem ${{ secrets.TEST_SSH_USER }}@${{ secrets.TEST_IP_ADDRESS }} "cd ~/${GITHUB_REPOSITORY##*/}/yandexgpt/ && echo "WHOAMI = Test" > .env && echo "RABBITMQ_DEFAULT_AGENT = ${{ secrets.RABBITMQ_DEFAULT_AGENT }}" >> .env && echo "RABBITMQ_DEFAULT_AGENT_PASS = ${{ secrets.RABBITMQ_DEFAULT_AGENT_PASS }}" >> .env && echo "YANDEXCLOUD_API_KEY = ${{ secrets.YANDEXCLOUD_API_KEY }}" >> .env"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Build
      run: |
        ssh -i private_key.pem ${{ secrets.TEST_SSH_USER }}@${{ secrets.TEST_IP_ADDRESS }} "cd ~/${GITHUB_REPOSITORY##*/}/yandexgpt/ && docker-compose build"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    
    - name: Re-launch
      run: |
        ssh -i private_key.pem ${{ secrets.TEST_SSH_USER }}@${{ secrets.TEST_IP_ADDRESS }} "cd ~/${GITHUB_REPOSITORY##*/}/yandexgpt/ && docker-compose down && docker-compose up -d"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}